server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle11g:1521:XE
    username: system
    password: oracle

mybatis:
  type-aliases-package: com.kosa.douzon_docker.vo
  mapper-locations:  classpath:mapper/*.xml